# Generated by Django 5.1.6 on 2025-02-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
