# Generated by Django 5.1.6 on 2025-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='bg_color',
            field=models.CharField(default='bg-yellow-400', max_length=20),
        ),
    ]
